### ISSUE TITLE
which CUDA version? GPU architectures supported？

### ISSUE THREAD

**Issue by lifeiteng** [NVIDIA/nv-wavenet#2]

**Comment by BrianPharris** [comment]
It requires CUDA 9.0 or later.  The Makefile targets the Volta architecture (sm_70) since Volta provides the best performance, but nv-wavenet will also run on Pascal architectures (sm_60 and sm_61).  You just need to change the ARCH assignment in the Makefile.  To determine which flag to use for your GPU, please refer to the compute capability chart at [https://developer.nvidia.com/cuda-gpus](https://developer.nvidia.com/cuda-gpus)
