### ISSUE TITLE
Fast Inference

### ISSUE THREAD

**Issue by PetrochukM** [NVIDIA/nv-wavenet#6]
Does this code base include: https://arxiv.org/abs/1611.09482?

A naive search of the repo turned up nothing concerning fast generation.

**Comment by BrianPharris** [comment]
Yes - nv-wavenet stores the intermediate results in a circular buffer in order to avoid redundant computation. 

 It differs from the approach described in the paper in that it just sizes the buffer for the worst-case dilation, meaning it is less space-efficient than using per-layer queues as described in the paper.
